### ISSUE TITLE
Uninstalling the Joplin snap deletes all user content

### ISSUE THREAD

**Issue by JanneM** [MrCarroll/joplin-desktop-snap#10]
I uninstalled the snap. As the storage location for all notes is in snap/joplin ..., removing the snap itself deletes all user content along with it. That's arguably not a good idea.

**Comment by JGCarroll** [comment]
I agree, but unfortunately this is a problem of Snaps in general. The sandbox policies prevent access to where Joplin would normally store data (Snaps can't access hidden top level folders in $HOME, so ~/.joplin for example), and there's an advantage to being in ~/snap/*/current/ as a snaps default $HOME, in that the database will be backed up every upgrade and can be rolled back to if desired in catastrophy situations. As long as Joplin itself doesn't offer the ability to change the folder internally, I'd rather not patch at it to change it any other way or there'd almost certainly be dataloss if I ever miss one instance.

Fortunately, snaps save a copy of all their data for a period of 31 days after you remove them, so you can actually restore your notes and then export them or copy the .joplin folder in ~/snap/joplin-james-carroll/ into $HOME, take a look at the restoring and automatic snapshot sections here https://snapcraft.io/docs/snapshots

**Comment by JanneM** [comment]
No worry - I was still just testing Joplin and the snap so I never lost any real data. And I didn't realize that the notes are stored in the database, not just as md files.

**Comment by alexanderadam** [comment]
So this cannot and probably won't be fixed, right? Can't this be closed then?

**Comment by JanneM** [comment]
Sure; I'll do it.
