### ISSUE TITLE
Snap does not load since last update

### ISSUE THREAD

**Issue by craffop** [MrCarroll/joplin-desktop-snap#25]
I am using kde-plasma desktop and since the last update "19 September 2023" 
It starts but nothing is loaded other than a blank screen. 
![joplin](https://github.com/MrCarroll/joplin-desktop-snap/assets/1289225/510629d0-87d8-40d8-94dd-df960194b5ac)

Not sure if this is related but I get this when I start it from the CLI 

Errors:
link failed but did not provide an info log
[8481:0925/191339.156499:ERROR:shared_context_state.cc(81)] Skia shader compilation error
------------------------
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 sk_RTAdjust;in float2 position;in half4 color;in float2 localCoord;flat out half4 vcolor_S0;noperspective out float2 vlocalCoord_S0;void main() {// Primitive Processor QuadPerEdgeAAGeometryProcessor
vcolor_S0 = color;vlocalCoord_S0 = localCoord;sk_Position = position.xy01;}
// Fragment SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform sampler2D uTextureSampler_0_S0;
flat in half4 vcolor_S0;noperspective in float2 vlocalCoord_S0;void main() {// Stage 0, QuadPerEdgeAAGeometryProcessor
half4 outputColor_S0;outputColor_S0 = vcolor_S0;float2 texCoord;texCoord = vlocalCoord_S0;outputColor_S0 = (blend_modulate(sample(uTextureSampler_0_S0, texCoord), outputColor_S0));const half4 outputCoverage_S0 = half4(1);{ // Xfer Processor: Porter Duff
sk_FragColor = outputColor_S0 * outputCoverage_S0;}}
// Vertex GLSL

**Comment by JGCarroll** [comment]
Hi,

Could you please try running `sudo snap refresh` to update to the 2.12.18 that's just released? I'm hoping that this might fix this without any further intervention.

Looking around, this generally appears to be a bug with Electron/Chromium on modern AMD systems with integrated Ryzen graphics, that can be fixed generally speaking by forcing Chromium to regenerate some of the GPU caches, which you could do with
```
rm $HOME/snap/joplin-desktop/current/.config/Joplin/GPUCache -r
```

However I'm hoping that just upgrading alone should make the `rm` unnecessary.

**Comment by craffop** [comment]
> Hi,
> 
> Could you please try running `sudo snap refresh` to update to the 2.12.18 that's just released? I'm hoping that this might fix this without any further intervention.
> 
> Looking around, this generally appears to be a bug with Electron/Chromium on modern AMD systems with integrated Ryzen graphics, that can be fixed generally speaking by forcing Chromium to regenerate some of the GPU caches, which you could do with
> 
> ```
> rm $HOME/snap/joplin-desktop/current/.config/Joplin/GPUCache -r
> ```
> 
> However I'm hoping that just upgrading alone should make the `rm` unnecessary.

Thank you, refreshing the snap has fixed the issue. 
Much appreciated.
