### ISSUE TITLE
Can not launch joplin-desktop in centOS

### ISSUE THREAD

**Issue by wenjie2024** [MrCarroll/joplin-desktop-snap#28]
hello, 
 
I have a issue with v2.13.15, when I want to launch joplin with 
`snap run joplin-desktop`, will get the following message:

`[17912:0227/235251.409667:ERROR:platform_thread_posix.cc(155)] pthread_create: Operation not permitted (1)
Trace/breakpoint trap (core dumped)`

can anyone help me on this? thanks a lot.

**Comment by JGCarroll** [comment]
Hi, sorry for the delay on this; there'd been other issues with the Joplin 2.14 snap release that consumed the majority of my free time the past 2 weeks.

Could you please try `sudo snap refresh` and see if the problem still occurs with 2.14.19? If it does, could you please let me know the output of `snap version`.

It's strange that this error occurs at all, usually I'd pin random errors on sandboxing and permissions but the sandboxing is looser in CentOS than e.g Ubuntu and there's no general permission errors even when the sandbox is fully operational, so at a moment I'd have nothing to guess as likely to be the problem but there's a chance the new update might just not have the same issue.

**Comment by wenjie2024** [comment]
> Hi, sorry for the delay on this; there'd been other issues with the Joplin 2.14 snap release that consumed the majority of my free time the past 2 weeks.
> 
> Could you please try `sudo snap refresh` and see if the problem still occurs with 2.14.19? If it does, could you please let me know the output of `snap version`.
> 
> It's strange that this error occurs at all, usually I'd pin random errors on sandboxing and permissions but the sandboxing is looser in CentOS than e.g Ubuntu and there's no general permission errors even when the sandbox is fully operational, so at a moment I'd have nothing to guess as likely to be the problem but there's a chance the new update might just not have the same issue.

**Comment by wenjie2024** [comment]
> Hi, sorry for the delay on this; there'd been other issues with the Joplin 2.14 snap release that consumed the majority of my free time the past 2 weeks.
> 
> Could you please try `sudo snap refresh` and see if the problem still occurs with 2.14.19? If it does, could you please let me know the output of `snap version`.
> 
> It's strange that this error occurs at all, usually I'd pin random errors on sandboxing and permissions but the sandboxing is looser in CentOS than e.g Ubuntu and there's no general permission errors even when the sandbox is fully operational, so at a moment I'd have nothing to guess as likely to be the problem but there's a chance the new update might just not have the same issue.

hi, thanks a lot for the replying. my snap version is 2.61.1-0.e17. please find the pic below as reference.
![Screenshot from 2024-03-09 16-39-29](https://github.com/MrCarroll/joplin-desktop-snap/assets/161181058/30a079b6-c1ee-4b88-ade0-e538e58c7f18)
